import { useState, useEffect } from 'react';
const API = "https://bharatcloud-api.sahilrana1940.workers.dev";
export default function App(){
  const [email,setEmail]=useState(localStorage.getItem("bharatcloud_email")||"");
  const [pass,setPass]=useState(""); const [logged,setLogged]=useState(!!localStorage.getItem("bharatcloud_email"));
  const [files,setFiles]=useState([]); const [msg,setMsg]=useState("");
  const loadFiles=async()=>{ const r=await fetch(`${API}/list`); const d=await r.json(); setFiles(d.files||[]); setMsg(`${d.files?.length||0} files`); };
  useEffect(()=>{ if(logged) loadFiles(); },[logged]);
  const handleLogin=()=>{ if(email==="admin@bharatcloud.com" && pass==="123456"){ localStorage.setItem("bharatcloud_email",email); setLogged(true);} else alert("Wrong password"); };
  const handleUpload=async(e)=>{ const file=e.target.files[0]; if(!file) return; const fd=new FormData(); fd.append("file",file); fd.append("name",`${Date.now()}-${file.name}`); setMsg("Uploading..."); await fetch(`${API}/upload`,{method:"POST",body:fd}); await loadFiles(); };
  const cleanName=(n)=>n.split('/').pop().replace(/^\d+-/,'');
  const handleShare=async(n)=>{ const link=`${API}/file/${encodeURIComponent(n)}`; await navigator.clipboard.writeText(link); if(navigator.share){ await navigator.share({title:cleanName(n),url:link}); } else alert("Link Copied: "+link); };
  if(!logged) return <div style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#0a0a0a",color:"#fff"}}><div style={{background:"#171717",padding:28,borderRadius:14,width:320,border:"1px solid #262626"}}><h2 style={{textAlign:"center"}}>BHARAT CLOUD ☁️</h2><input style={{width:"100%",padding:10,marginTop:15,borderRadius:8}} placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input style={{width:"100%",padding:10,marginTop:10,borderRadius:8}} type="password" placeholder="Password" value={pass} onChange={e=>setPass(e.target.value)}/><button onClick={handleLogin} style={{width:"100%",padding:10,marginTop:12,background:"#ff7a18",color:"#fff",border:0,borderRadius:8}}>Login</button></div></div>;
  return <div style={{maxWidth:850,margin:"0 auto",padding:20,background:"#0a0a0a",color:"#fff",minHeight:"100vh"}}><h2>BharatCloud Pro v14.1 ✅</h2><div style={{background:"#171717",padding:14,borderRadius:12,marginTop:10,border:"1px solid #262626"}}><input type="file" onChange={handleUpload}/> <span style={{color:"#4ade80",marginLeft:10}}>{msg}</span></div><div style={{marginTop:20}}>{files.map(f=><div key={f.name} style={{border:"1px solid #262626",background:"#171717",padding:12,borderRadius:10,display:"flex",gap:10,alignItems:"center",marginBottom:8}}><img src={`${API}/file/${encodeURIComponent(f.name)}`} style={{width:45,height:45,objectFit:"cover",borderRadius:8}}/><div style={{flex:1,overflow:"hidden"}}><div style={{fontWeight:600,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{cleanName(f.name)}</div><div style={{fontSize:11,opacity:.5}}>{(f.size/1024).toFixed(1)} KB</div></div><a href={`${API}/file/${encodeURIComponent(f.name)}`} target="_blank" style={{background:"#fff",color:"#000",padding:"6px 10px",borderRadius:7,textDecoration:"none",fontSize:12}}>Open</a><button onClick={()=>handleShare(f.name)} style={{background:"#333",color:"#fff",padding:"6px 10px",borderRadius:7,border:"1px solid #444",fontSize:12}}>Share</button><button onClick={async()=>{await fetch(`${API}/delete/${encodeURIComponent(f.name)}`,{method:"DELETE"}); loadFiles();}} style={{background:"#ef4444",color:"#fff",padding:"6px 10px",borderRadius:7,border:0,fontSize:12}}>Delete</button></div>)}</div></div>;
}
